/**
 * Copyright 2001-2007 by CreamTec, LLC. All rights reserved
 * Add your custom JavaScript functions here. This script is included into every page
 */

// Called from onLoad function that is generated by AjaxSwing
function customOnLoad()
{
}


// Called from doSubmit function before a page is submitted by AjaxSwing
function customOnSubmit()
{
}

// Called when AJAX response has been received and processed by AjaxSwing
function customOnAjaxComplete(responseData) {

}

// Called when IFrame that used on page Loaded
function customOnIFrameLoaded(e)
{

}
